Repository mattermost/matterbuild, pull requests merged in 2020-06, with the labels that each got.

#35 MM-25669 - Matterbuild cutplugin always requires --force for tags that match an existing tag prefix
  server/plugin_release.go
  server/plugin_release_test.go
Labels: 3: Reviews Complete

#31 Containerize project and publish to DockerHub
  .circleci/config.yml
  Dockerfile
  Makefile
  README.md
  server/server.go
Labels: 3: Reviews Complete, AutoMerge, Enhancement

#36 Fix docker build CI
  .circleci/config.yml
Labels: Enhancement

#37 Add k8s manifests and dev tooling
  .gitignore
  Dockerfile
  Makefile
  README.md
  Tiltfile
  config.json
  deploy/base/deployment.yaml
  deploy/base/kustomization.yaml
  deploy/base/rbac.yaml
  deploy/base/service.yaml
  deploy/config/kustomization.yaml
  deploy/overlays/dev/kustomization.yaml
  deploy/overlays/prod/ingress.yaml
  deploy/overlays/prod/kustomization.yaml
  deploy/overlays/prod/service.yaml
  server/log.go
Labels: 3: Reviews Complete, Enhancement

#38 Use Ambassador for ingress-controller
  Makefile
  deploy/base/service.yaml
  deploy/overlays/dev/kustomization.yaml
  deploy/overlays/dev/service.yaml
  deploy/overlays/prod/ingress.yaml
  deploy/overlays/prod/kustomization.yaml
  deploy/overlays/prod/service.yaml
Labels: 2: Dev Review, Enhancement

#40 Add release targets and script
  Makefile
  README.md
  deploy/overlays/prod/kustomization.yaml
  scripts/release.sh
Labels: 2: Dev Review
